modLoader="javafml"
loaderVersion="[47,)"
license="GPL v3.0"

[[mods]]
modId="gts"
version="3.1.1-forge"
displayName="Toki (Forge Port)"
displayURL="https://mcreator.net"
credits="Censhucho, Forge port by Ghost_chu"
authors="Dukea, Censhucho, Ghost_chu, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.gts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.gts]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gts]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration